info:
  name: serviceapi microservice
  description: this is a development from serviceapi
  version: 1.0.0

contactdetails:
  description: this is development profiling
  supportProviders:
    name1: Gebre Reda
    name2: Hadis Melless
    Name3: Nainael W/giorges
  supportPhoneCalls:
    - 641-233-9801
    - 642-233-9802
    - 643-233-9803